### PR TITLE
Support `textStyle.lineSpacing`

### LINKED ISSUE #41: Support line spacing
Hi! Thanks for this super helpful tool!

I'm currently building templates for an Android app. In Zeplin the line height is defined for some of our text styles (e.g. 18.2) with a text size of e.g. 15. To configure this in Android we need to have the "line spacing extra" being 3.2 in this example (18.2 - 15).

It would be great to do something like `{{% textStyle.lineHeight - textStyle.fontSize  %}}` or a similar syntax.

### PR DESCRIPTION
**Pull request by freak4pc**
Resolves #41

### CODE REVIEW

**Comment by freak4pc** [comment]
@crysxd Would be happy if you have a few moments to test this branch :)

**Comment by crysxd** [comment]
I'll give it a shot in 5 minutes. As this new property mirrors the Android property, calling it `lineSpacingExtra` would be more accurate I think!

**Comment by crysxd** [comment]
@freak4pc Works flawlessly!

```
<item name="android:lineSpacingExtra">{{% textStyle.lineSpacing %}}sp</item>
```

results in 

```
<item name="android:lineSpacingExtra">3.2sp</item>
```

**Comment by freak4pc** [comment]
Nice, glad to hear! I'll cut a release soon:) 

About the name, I don't mean for it to directly mirror Android and it seems the more common term is simply line spacing (in print, design, CSS and other platforms) so I think sticking with this would be more generic. 

Thanks for the great feedback, though!

**Comment by crysxd** [comment]
Thanks a lot! That really solved the last issue we had with prism! :)

**Comment by freak4pc** [comment]
Happy to help! Let me know if you bump into anything else ;-)

**Comment by freak4pc** [comment]
This is part of 0.5.0 :)

**Comment by crysxd** [comment]
Thanks! Your speed is truly impressive :D 
Installed the new version from Homebrew and it works like a charm :)

**Pull request merged**
